version: '3.7'

services:
  master:
    build:
      context: ../../
      dockerfile: ./cmd/master/Dockerfile
    ports:
      - 1337:1337
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./secrets.env
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./secrets.env